# Feature Engineering

#### Import the required libraries

In [1]:
# Pandas for DataFrames
import pandas as pd
pd.set_option('display.max_columns', 100)

# Matplotlib for visualization
from matplotlib import pyplot as plt

# display plots in the notebook
%matplotlib inline

# Seaborn for visualization
import seaborn as sns

#### Import the cleaned dataset

In [2]:
# Load cleaned dataset from the previous lecture
df = pd.read_csv('cleaned_df.csv')
df.head(2)

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,property_type
0,295850,2013,234,81,1,1,584,2013,0,0,Condo
1,216500,2006,169,51,1,1,612,1965,0,0,Condo

## Check The Statistics

In [3]:
df.describe()

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement
count,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000,1879.000000
mean,423055.182012,2007.105907,467.211815,140.589675,3.423097,2.582757,2331.374135,1982.988824,12769.701437,0.813731
std,151537.541376,5.197993,231.705973,72.947560,1.068136,0.944374,1337.336152,20.272383,35329.353444,0.389427
min,200000.000000,1993.000000,88.000000,30.000000,1.000000,1.000000,500.000000,1880.000000,0.000000,0.000000
25%,300000.000000,2004.000000,321.000000,94.000000,3.000000,2.000000,1347.000000,1970.000000,1542.000000,1.000000
50%,392235.000000,2007.000000,426.000000,125.000000,3.000000,3.000000,1908.000000,1986.000000,6098.000000,1.000000
75%,525250.000000,2011.000000,570.500000,169.000000,4.000000,3.000000,3006.500000,2000.000000,11761.000000,1.000000
max,800000.000000,2016.000000,4508.000000,1374.000000,5.000000,6.000000,8450.000000,2015.000000,436471.000000,1.000000

## I. Domain Knowledge

#### A. Popular Properties

2 bedroom and 2 bathroom properties are especially popular for investors. Let's create an indicator variable just for properties with 2 beds and 2 baths.

Build your code step by step. Here's how:

* Your first condition `df.beds == 2`
* Your second condition `df.baths == 2`
* Combine the two conditions with an `&` operator
* Convert the resulting data to `int` type.
* Store the result in a new column called **popular**

In [4]:
((df.beds == 2)&(df.baths == 2)).astype(int)

0       0
1       0
2       0
3       0
4       0
       ..
1874    0
1875    0
1876    0
1877    0
1878    0
Length: 1879, dtype: int64

In [5]:
# Create indicator variable for properties with 2 beds and 2 baths
df['popular']= ((df.beds == 2)&(df.baths == 2)).astype(int)
df.sample(6)

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,property_type,popular
1031,225000,2011,339,87,4,2,1800,1981,10454,1,Bunglow,0
165,237500,2014,198,60,2,2,886,1982,0,0,Condo,1
1056,345000,2012,387,99,4,2,2040,1974,7840,1,Bunglow,0
303,267000,2010,237,72,2,2,1360,1967,0,0,Condo,1
1720,429625,2003,492,139,5,3,4884,2003,13939,1,Bunglow,0
1784,280000,1998,676,206,5,4,4400,1977,26571,1,Bunglow,0

In [6]:
# Check how many properties have 2 baths and 2 beds
df.popular.value_counts()

popular
0    1701
1     178
Name: count, dtype: int64

#### B. Housing Market Recession

We are modeling housing prices in the United States, it's important to consider the housing market recession around 2008. According to data from Zillow, the lowest housing prices were from 2010 to end of 2013.

<br>
Create an indicator feature **recession**

Here's how:
* Your first condition `year_sold >= 2010`
* Your second condition `year_sold <= 2013`
* Combine the two conditions with an `&` operator
* Convert the resulting data to `int` type.
* Store the result in a column called **recession**

In [7]:
# Create a new variable recession
df['recession'] = ((df.year_sold >= 2010) & (df.year_sold<=2013)).astype(int)
df.sample(6)

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,property_type,popular,recession
1719,480496,2011,533,137,5,3,4873,2011,16988,1,Bunglow,0,1
372,275000,2005,167,47,3,1,1280,1984,1598,1,Bunglow,0,0
297,525000,2006,414,143,2,2,1320,1974,0,0,Condo,1,0
588,399900,2005,354,91,3,2,1810,1988,2178,1,Bunglow,0,0
1267,500000,2016,611,212,4,3,2352,1982,9243,1,Bunglow,0,0
458,350000,2005,389,118,3,2,1340,1965,10497,1,Bunglow,0,0

In [8]:
# Check how many propoerties were sold during recession period
df.recession.value_counts()

recession
0    1384
1     495
Name: count, dtype: int64

## II. Interaction Features

In the first step, you engineered features from domain knowledge. interaction features can be products, sums, or differences between two features.

#### A. Property Age

We have the features `year_sold` and the `year_built`. let's create a new feature `property_age`

In [9]:
# Create a property age feature
df['property_age'] = df.year_sold - df.year_built
df.head(2)

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,property_type,popular,recession,property_age
0,295850,2013,234,81,1,1,584,2013,0,0,Condo,0,1,0
1,216500,2006,169,51,1,1,612,1965,0,0,Condo,0,0,41

Do a quick sanity check on that feature. Run `df.describe()` and check the stats for the feature `property_age`

In [10]:
# Do you see any error?
df[['popular','recession','property_age']].describe()

           popular    recession  property_age
count  1879.000000  1879.000000   1879.000000
mean      0.094731     0.263438     24.117084
std       0.292921     0.440615     21.142781
min       0.000000     0.000000     -8.000000
25%       0.000000     0.000000      6.000000
50%       0.000000     0.000000     20.000000
75%       0.000000     1.000000     38.000000
max       1.000000     1.000000    114.000000

In [11]:
# Check number of observations with 'property_age' < 0
(df.property_age < 0).value_counts()

property_age
False    1860
True       19
Name: count, dtype: int64

In [12]:
df[df.property_age<0]

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,property_type,popular,recession,property_age
403,280000,2005,211,59,3,2,1040,2013,14810,1,Bunglow,0,0,-8
1136,294996,2002,413,117,4,2,3711,2003,7405,1,Bunglow,0,0,-1
1455,461000,2003,616,158,4,3,4301,2004,9583,1,Bunglow,0,0,-1
1536,395000,2014,1188,362,4,4,4674,2015,9100,1,Bunglow,0,0,-1
1552,300000,2000,1799,548,4,4,5800,2002,22215,1,Bunglow,0,0,-2
1568,540000,2005,868,264,4,6,4418,2007,11325,1,Bunglow,0,0,-2
1714,550000,2005,1200,349,5,3,4681,2006,11761,1,Bunglow,0,0,-1
1778,350000,2003,739,225,5,4,4252,2010,22215,1,Bunglow,0,0,-7
1794,550000,2005,860,262,5,4,4693,2006,16988,1,Bunglow,0,0,-1
1805,400000,2012,1217,371,5,4,5003,2013,21344,1,Bunglow,0,1,-1
1822,570000,2011,1147,349,5,4,5480,2012,11325,1,Bunglow,0,1,-1
1824,365000,2007,799,243,5,4,5654,2015,10175,1,Bunglow,0,0,-8
1860,320000,2013,1057,322,5,5,5984,2015,16988,1,Bunglow,0,1,-2
1862,231000,2010,799,243,5,5,6346,2011,10890,1,Bunglow,0,1,-1
1866,280000,2010,860,262,5,5,6542,2011,43995,1,Bunglow,0,1,-1
1868,649000,2005,1146,349,5,5,7034,2006,25700,1,Bunglow,0,0,-1
1870,370000,2004,1045,318,5,5,7578,2008,87120,1,Bunglow,0,0,-4
1873,555000,2003,1966,599,5,5,8450,2004,91911,1,Bunglow,0,0,-1
1874,385000,2002,1250,381,5,6,6381,2004,224334,1,Bunglow,0,0,-2

On second thought, this could be an error or that some homeowners buy houses before the construction company builts them. But for the purpose of this project we will remove these observations.

We'll do a quick ad-hoc data cleaning and remove these observations from our dataset.

#### Remove observations where `property_age` is less than 0.
* Keep only observations where `property_age` is 0 and above.

In [13]:
# Remove rows where property_age is less than 0
df = df[df.property_age >= 0]

In [ ]:
# if you want to use .drop()
#df.drop(index=df[df.property_age<0].index, inplace=True)

In [14]:
df.head(2)

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,property_type,popular,recession,property_age
0,295850,2013,234,81,1,1,584,2013,0,0,Condo,0,1,0
1,216500,2006,169,51,1,1,612,1965,0,0,Condo,0,0,41

## III. Dummy Variables

Most Machine Learning algorithms cannot handle text data. Therefore, we need to create what are called **dummy variables** for all our categorical features.
<br><br>
Pandas has an easy function for doing this automatically.
* `pd.get_dummies()`

In [15]:
df.head(2)

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,property_type,popular,recession,property_age
0,295850,2013,234,81,1,1,584,2013,0,0,Condo,0,1,0
1,216500,2006,169,51,1,1,612,1965,0,0,Condo,0,0,41

In [16]:
df2 = df.copy()

In [17]:
# Create dummy variables for 'property_type'
df = pd.get_dummies(df, columns=['property_type'], drop_first=True).astype(int)
df.head(2)

,price,year_sold,property_tax,insurance,beds,baths,sqft,year_built,lot_size,basement,popular,recession,property_age,property_type_Condo
0,295850,2013,234,81,1,1,584,2013,0,0,0,1,0,1
1,216500,2006,169,51,1,1,612,1965,0,0,0,0,41,1

In [18]:
# final check
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1860 entries, 0 to 1878
Data columns (total 14 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   price                1860 non-null   int64
 1   year_sold            1860 non-null   int64
 2   property_tax         1860 non-null   int64
 3   insurance            1860 non-null   int64
 4   beds                 1860 non-null   int64
 5   baths                1860 non-null   int64
 6   sqft                 1860 non-null   int64
 7   year_built           1860 non-null   int64
 8   lot_size             1860 non-null   int64
 9   basement             1860 non-null   int64
 10  popular              1860 non-null   int64
 11  recession            1860 non-null   int64
 12  property_age         1860 non-null   int64
 13  property_type_Condo  1860 non-null   int64
dtypes: int64(14)
memory usage: 218.0 KB

We will save this dataset and train our model on it.

Use pandas function `.to_csv()` and remember to set index=None

In [ ]:
# Save the data as 'final.csv'
df.to_csv('final.csv', index=None)